apiVersion: v1
kind: Endpoints
metadata:
  name: mysql-metrics
  namespace: monitoring
  labels:
    k8s-app: node-mysql
subsets:
  - addresses:
    - ip: 192.168.37.10
    ports:
    - name: mysql
      port: 9104
      protocol: TCP
