apiVersion: v1
kind: Service
metadata:
  name: mysql-metrics
  namespace: monitoring
  labels:
    k8s-app: node-mysql
spec:
  type: ClusterIP
  ports:
  - name: mysql
    port: 9100
    protocol: TCP
    targetPort: 9100
